name: ci-working-example

on:
  push:
    branches:
      - main

env:
  DAREBOOST_API_TOKEN: ${{ secrets.DAREBOOST_API_TOKEN }}
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

jobs:
  lint:
    uses: ./.github/workflows/linter.yaml

  example:
    needs: [lint]
    runs-on: [self-hosted, docker]

    steps:
      - name: Build
        run: docker build -t owner/heart:standard .

      - name: Start container
        run: >
          docker run
          --rm
          --name heart-container
          -v "$(pwd)/ci/heart/config:/usr/heart/config"
          -e SLACK_CHANNEL_ID=${{env.SLACK_CHANNEL_ID }}
          -e DAREBOOST_API_TOKEN=${{ env.DAREBOOST_API_TOKEN }}
          -e SLACK_API_TOKEN=${{ env.SLACK_API_TOKEN }}
          fabernovel/heart:standard
