name: Lint Code

on: [workflow_call]

jobs:
  build:
    runs-on: [self-hosted, docker]
    container:
      image: docker://ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Super Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          USE_FIND_ALGORITHM: true
          VALIDATE_GITHUB_ACTIONS: true
          LINTER_RULES_PATH: /.github/
          GITHUB_ACTIONS_CONFIG_FILE: actionlint.yaml
